[package]
name = "wabba-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
wabba-protocol = { path = "../wabba-protocol" }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4.5.53", features = ["derive"] }
log = "0.4.28"
env_logger = "0.11.8"
