[package]
name = "wabba-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
zip = "4.1.0"
log = "0.4.28"
serde = { workspace = true }
serde_json = { workspace = true }
md5 = "0.7"
xxhash-rust = { version = "0.8.15", features = ["std", "xxh64"] }
base64 = "0.22.0"
